### ISSUE TITLE
Support convert(GPUArray, A)

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGPU/GPUArrays.jl#113]
It would be nice to be able to write architecture-independent code via 
```julia
A = randn(100)
A_GPU = convert(GPUArray, A) # Would be CLArray on AMD and CuArray on NVidia
```

Also,` GPUArray(A)` should work the same. At the moment we get an error:
```julia
ERROR: MethodError: no method matching similar(::Type{GPUArrays.GPUArray}, ::Type{Float32}, ::Tuple{Int64,Int64})
Closest candidates are:
  similar(::Array, ::Type, ::Tuple{Vararg{Int64,N}}) where N at array.jl:194
  similar(::SubArray, ::Type, ::Tuple{Vararg{Int64,N}} where N) at subarray.jl:58
  similar(::Base.ReshapedArray, ::Type, ::Tuple{Vararg{Int64,N}} where N) at reshapedarray.jl:167
  ...
Stacktrace:
 [1] convert(::Type{GPUArrays.GPUArray}, ::Array{Float32,2}) at /Users/sheehanolver/.julia/v0.6/GPUArrays/src/construction.jl:91
```

**Comment by dlfivefifty** [comment]
How I would implement it: in CLArrays.jl add the line
```julia 
convert(::Type{GPUArray}, A) = convert(CLArray, A)
```
And similarly in CuArrays.jl. This is technically type piracy, but will anyone ever use both packages at the same time?

**Comment by SimonDanisch** [comment]
I think there is a good chance, that people might be forced to use CLArrays + CuArrays in the future together. But it's unlikely enough to just go with this solution - I like how it doesn't have any global variable and `just works`. @MikeInnes what do you think?

**Comment by MikeInnes** [comment]
No, not a good idea to add a method that will clash – there are many reasons to want to have both packages loaded.

At some point, you have to do `using CuArrays` or `using CLArrays`, so just after that you can write `gpu(x) = cu(x)` or `gpu(x) = cl(x)`. The rest of your code can then use `gpu(x)` so that things are platform agnostic.

**Comment by ChrisRackauckas** [comment]
Clashing would always throw a redefinition warning too which just looks bad.

>This is technically type piracy, but will anyone ever use both packages at the same time?

CuArrays is faster on GPUs, but CLArrays works on more devices. It's not an over-optimization to mix them when necessary, in fact I could see it being a pretty significant difference if CuBLAS/CUDNN stays so far ahead of what OpenCL has.

**Comment by ChrisRackauckas** [comment]
>The problem with your suggestion is that it doesn't work nicely in packages, where the machine is determined by users.

Why not just have users pass in the array then? In DiffEq it's a CLArray if I'm given a CLArray, or a CuArray if I'm given a CuArray, or a ...

**Comment by dlfivefifty** [comment]
> Why not just have users pass in the array then? 

Because the package code might generate the `GPUArray`. Imagine a package that creates finite-difference banded matrices on the GPU. The user-facing code should look something like:
```julia
using CLArrays, GPUFiniteDifferences
clarrays() # sets a global?

Δ = gpu_finite_difference(100)
```

And then in GPUFiniteDifferences a quick-and-dirty implementation would be:
```julia
function gpu_finite_differences(n) 
   A = convert(GPUArray{Float32}, Zeros(3,n))
   A[1,:] = 1/n^2
   A[end,:] = 1/n^2
   BandedMatrix(A,(1,1))
end
```

The cleanest alternative would be
```julia
using CLArrays, GPUFiniteDifferences

Δ = gpu_finite_difference(CLArray, 100) # pass in the type
```
but this might get annoying.

**Comment by ChrisRackauckas** [comment]
I think relying on globals just ends up with problems. BigFloats uses a global precision and it's the first thing people want to change about its implementation since then it's not thread-safe. And Plots.jl's design isn't something to follow. It's being replaced with Makie.jl which uses local backend choices so that way different plots can go on different backends and it fixes the compilation issues. Relying on a global here could give the same composition and compilation issues that Plots.jl has. 

I think the issue is that your proposed API is still mixing single and multiple dispatch ideas. If you just have  `function finite_difference(n,T=Array{Float64})`, then it's pretty explicit that `finite_difference(100,CLArray{Float32})` will work and dispatches can appropriately speed up certain interactions. This also highlights that bit type among other things needs be chosen and maybe mixed depending on the application (complex and reals?). In the end, I only tend to see global type information cause issues.

On the user side, @MikeInnes 's `gpu(x)` function, or just setting `const GPU_TYPE = CLArray` makes user scripts just as easy to swap, so I don't think the Plots.jl style really has an advantage here.

**Comment by maleadt** [comment]
With https://github.com/JuliaGPU/CuArrays.jl/pull/172 and https://github.com/JuliaGPU/GPUArrays.jl/pull/169 I've been moving in the opposite direction, ref. Base.AbstractArray, using GPUArray as a purely abstract type for dispatch purposes but without concrete functionality. That didn't evoke any comments, so let's close this issue?

**Comment by dlfivefifty** [comment]
Sure
