### ISSUE TITLE
Improve adaption of GPUArrays

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/GPUArrays.jl#142]
It has been bugging me, that people naturally start using `CUDAnative.@cuda f(args...)` instead of  `GPUArrays.gpu_call`.

This certainly has been my fault, because I haven't been advertising it a lot, there is no great documentation and there has been a dark time recently for GPUArrays + 0.7 support - and it's likely also @maleadt fault by doing an excellent job at making CUDAnative rock solid and well documented!

But I do think we should invest into making `gpu_call` the default!

## Advantages:

* one can debug kernels on the CPU with JLArray - I honestly couldn't be productive without that
* we could further improve JLArray to record access patterns + detect race conditions with minimal effort
* CLArrays + hypothetical other backends *just work* - e.g. it would be almost trivial to add a decent multi threading backend - which I do actually plan to do soon ;)
* No ecosystem divide - It's kind of trivial to port a cudanative kernel to GPUArrays, but then again it's annoying work and from the user perspective, a cuda gpu kernel in the wild won't just automatically work for them with other backends
* since `gpu_call` just routes directly to `@cuda` it's trivial to just use `gpu_call`. I'm totally fine with people using cuda intrinsics in such "hardware independent" kernels making them not work on other platforms - it'd still be a step up from not using the API at all! Then it's much easier to just go to that kernel and replace the intrinsics - or decide to overload it differently for other backends. Which is easily possible via the state object we can dispatch the kernel on.

To make this more pleasant I realize we might want to change a few things!

## Redesign

* redesign the api + name of gpu_call https://github.com/JuliaGPU/GPUArrays.jl/issues/133
* Make CuDynamicMem work! As I understand it, CUDAs dynamic memory is just a big static memory one can allocate at call time, to which one can get views on the device - so a first version could be implemented by making views into device arrays work - which we probably should try anyways! 
* the state argument is a bit awkward - maybe we can get rid of it with some magic, e.g. cassette
* the array one needs to pass for dispatch reasons is equally awkward. We could try to search for a GPUArray in the args and use the queue/ctx of that one - and if none is found use the default ctx. We could also make `(blocks, threads)` mandatory and for the use case I'm current offering in `gpu_call` (call `f` length(a) times), we could start offering more high level constructs for cartesian + gridded iteration over GPUArrays - which would be a lot cleaner and maybe we can make the good ol' `thread/block_idx` much easier to use for newcomers.

Then we should document this in both cuarrays + cudanative ;)

What does everyone think?

CC: @vchuravy, @maleadt, @maleadt, @andreasnoack, @jekbradbury

**Comment by maleadt** [comment]
Not sure I agree. First, I've always had a bad feeling about GPU_Arrays_ defining a cross-vendor `gpu_call` -- that's not an array abstraction. Second, performance is key with GPUs, and I don't trust vendor-neutral abstractions to be zero-cost. I'd rather have a well-defined API of composable kernels, implemented using fast, vendor-specific code to be used as the basis for a cross-platform array package.

> a first version could be implemented by making views into device arrays work

That's going to be horribly slow, global vs local memory. And not great as a starting point if we never manage to get past that because of hardware reasons.

Don't get me wrong, I'm all for a vendor-neutral GPU array abstraction, but I don't think that should be built on top of vendor-neutral kernels. Easier said than done, of course.

**Comment by SimonDanisch** [comment]
>That's going to be horribly slow, global vs local memory. And not great as a starting point if we never manage to get past that because of hardware reasons.

So I guess I am misunderstanding, that CuDynamicMem could be implemented with a large CuStaticMemory + an offset? In any case, I'm not sure what the problem is - if it's slow and cuda has a fast implementation, you should just be able to overload that, right?

>but I don't think that should be built on top of vendor-neutral kernels

That's why I'm all for people using vendor specific stuff with `gpu_call`. Using the exact same API for 90% of the kernel & invocation would bring us quite far. And as I said, it is possible to have the same launch code and then just dispatch to different kernels. And if the launch code needs to be changed drastically as well, we can also quite easily do that via dispatch!
 
I basically just want to lower the bar here. And actually, there is a lot of functionality that will work perfectly fine with vendor neutral kernels and max performance... In all those years, we managed to write ~1 kernel which is a bit faster than the vendor neutral version. So there is definitely a broad range of kernels we can write vendor neutral. 
We could also start thinking more about compiler passes, that turn vendor neutral code into code that is using the right intrinsics - after all nobody wants to use some weird intrinsic that changes with each hardware version. And of course composable kernels, that dispatch to high performance implementations - but that is orthogonal to the kind of API convergence I'm talking about here.

**Comment by SimonDanisch** [comment]
Btw, the state object I try to pass around could also be used to dispatch to different kernels for different hardware generations. After all, even inside CUDA a new generation is basically a new platform ;)

**Comment by SimonDanisch** [comment]
>defining a cross-vendor gpu_call -- that's not an array abstraction.  

I always felt arrays are so crucial, that we might as well combine it with other crucial stuff - but of course you're right!

Would you be more open to it, if we move this part of the API to it's own package - and directly depend on it in CUDAnative?

**Comment by maleadt** [comment]
Though, the fact that these kernels live in GPUArrays.jl shows that it can work, kinda, since performance hasn't been properly vetted. Just to say that I don't fully oppose the current model, I just don't think that it'll scale once people want to optimize for performance. Having a well-defined set of kernels (probably not too different from the list above) would make it easier to have high-performance vendor-specific reimplementations, and layer array-based abstracions on top of that in a vendor-neutral package like GPUArrays.

**Comment by lcw** [comment]
I would like to make a few comments just as a potential user of a vendor-neutral gpu interface.

When I first started trying to write vendor neutral code, in C, it was riddled with ifdefs everywhere.  Later I used [OCCA](https://libocca.org/) as a vendor-neutral gpu interface with some success.

For me there are two things to buy into.  There is the host abstraction and the kernel abstraction.  I have found the host abstraction useful for reducing the need for ifdefs in my code.  I think the OpenCL abstraction is pretty good for this.

I have mixed feelings about vendor-neutral kernels.  For debugging it is nice to have the same kernel  execute in a GPU context and in a Julia context.  Also, usually only 3 or 4 kernels are the performance bottleneck for many of the codes I write.  So having the rest in a vendor neutral format speeds up moving the code to a new device.

For performance portability, however, you may want to have kernels tailored to the device and you want to be able to use backend specific things (e.g., shuffle).  So even if you have the best kernel abstraction, for performance reasons the kernels are going to be device dependent.  So I would like to see any host abstraction support backend specific kernels if possible.

Further, for generic kernels it is interesting to think about disconnecting what operations need to be executed and the schedule of their execution ([Loo.py](https://mathema.tician.de/software/loopy/) is an attempt at doing this).

**Comment by jekbradbury** [comment]
In the ML world, CUDA has won so convincingly that every tool that seeks to support AMD is doing so through ROCm, i.e. AMD's effort to target native CUDA code. Unfortunately for our purposes, what it targets is CUDA C rather than NVPTX.

From my perspective: the ability to test and debug a kernel with JLArrays is pretty fantastic, but the requirement to rewrite things in a way that allows Transpiler to work isn't great. I'd really rather avoid having to turn code like
```julia
function mapreducedim_kernel(f, op, R, A, range)
    I = @cuindex R
    newrange = map((r, i) -> r === nothing ? i : r, range, I)
    for I′ in CartesianIndices(newrange)
        @inbounds R[I...] = op(R[I...], f(A[I′]))
    end
    return
end
```
into
```julia
@generated function mapreducedim_kernel(state, f, op, R, A, range::NTuple{N, Any}) where N
    types = (range.parameters...,)
    indices = ntuple(i-> Symbol("I_$i"), N)
    Iexpr = ntuple(i-> :(I[$i]), N)
    body = :(@inbounds R[$(Iexpr...)] = op(R[$(Iexpr...)], f(A[$(indices...)])))
    for i = N:-1:1
        idxsym = indices[i]
        if types[i] == Nothing
            body = quote
                $idxsym = I[$i]
                $body
            end
        else
            rsym = Symbol("r_$i")
            body = quote
                $(rsym) = range[$i]
                for $idxsym in Int(first($rsym)):Int(last($rsym))
                    $body
                end
            end
        end
        body
    end
    quote
        I = @cartesianidx R state
        $body
        return
    end
end
```

**Comment by SimonDanisch** [comment]
Oh yeah of course - if the upper won't work in the future, the OpenCL transpiler is a lost cause ;)
The good news is, that I started being able to use Julia's optimized IR with forced inlining, which should be pretty resiliant against more high level constructs.

Anyways, my recommendation is to not change code for the transpiler if possible, so I might want to move such monsters to CLArrays (if I remember correctly, that kernel was mostly working, so I was giving up the hope to have it like the cuda kernel pretty late).

**Comment by ChrisRackauckas** [comment]
I just don't see how vender-neutral kernels fit into GPUArrays. GPUArrays give you an array type with a lot of nice vectorized calls defined on them, and broadcast. Whether it's a CuArray or a CLArray, I take how the `fft` is implemented as a blackbox I don't have to think about. They work well in generic array codes. Generic array codes aren't going to write a vender-neutral kernel because then it won't work with most other array types (non-GPUArrays), and most people just want the fastest vectorized function calls that the GPUArray type can provide (so it should be calling CUDNN, or writing some optimized CUDA code, in the background).

In total, it's cool you got it working, but I think it's by far the least useful part of GPUArrays but also probably the hardest and most time consuming part of GPUArrays. I hope that's not too discouraging.

**Comment by SimonDanisch** [comment]
Going forward, I will have much less time for CLArrays - in other words, if we don't establish some APIs to make it easier to get new CUDA ML efforts magically work in CLArrays, I might as well stop working on it.

@ChrisRackauckas, this isn't directly about the user, it's more about how (if?) we can offer multiple platform support with the few people we have working on this. 

I'll need to put at least a whole weekend (possibly of my own time) into upgrading Transpiler.jl to work with 1.0 - if I don't have the feeling that this effort is carried by everyone working on the GPU ecosystem, I might as well go on a canoe trip instead ;) 

Btw, @maleadt and I had a pretty productive discussion and we came to the conclusion, that we can get pretty far with a solid cartesian iteration kernel + cassette rewrites of hardware specific functions.

Actually, the cassette rewrites are pretty similar to what I had in mind with dispatching on a state object - it will just remove the cumbersome state object, but will still need some discussion about how to name our composable kernels.
I think we can see this as an opportunity to establish nice APIs for composable high performance kernels.

This is roughly how this could look:

```Julia
function reduce_kernel(...)
    block_reduce(...)
end
shmem_reduce(args...) = ....
shfl_reduce(args...) = ....
Cassette.overdub(::CLContext, block_reduce, args...) = shmem_reduce(args...)
Cassette.overdub(::CUDA{7.0}, block_reduce, args...) = shfl_reduce(args...)
```

**Comment by vchuravy** [comment]
Yes the Cassette solution is what I had in mind when I brought up the topic on last weeks call.
I am still a proponent of having generic kernels (which can be replaced by high-performance hardware specific kernels) since I have one or two projects in the pipeline that will benefit from having them available.

**Comment by jkozdon** [comment]
So I have been playing around with GPUArrays, and really like the idea of a vendor-neutral interface.

I've noticed though that the CPU backend seems to be rather poor. Is there any thought to improve this? For example allocating a `JLArray` and filling it has drastically different performance than an `Array`

```
julia> A = Array{Float64}(undef, 1000000);

julia> @time fill!(A, 0);
  0.004177 seconds (4 allocations: 160 bytes)

julia> B = JLArray{Float64}(1000000);

julia> @time fill!(B, 0);
  0.863657 seconds (6.03 M allocations: 687.883 MiB, 13.18% gc time)
```

From what I can tell the poor performance is coming from the `@async` command as well as the state variable.

Would be nice if I could get performance of a code using JLArrays to match that of native Julia. Not looking for portable performance of the kernels, more performance of the data types. So that at least my GPU kernels, are not terrible when run on the CPU.

That said, not sure what the fix is...
