### ISSUE TITLE
cached_state not defined

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/GPUArrays.jl#174]
Hi,

What is the replacement for `cached_state` ? I used it to provide the last argument in `GPUArrays.gpu_rand`.

Thank you,

Best

**Comment by SimonDanisch** [comment]
I guess you're running into this redesign:
https://github.com/JuliaGPU/GPUArrays.jl/pull/167

**Comment by rveltz** [comment]
Thank you for the response! But, wihtout example nor test, how am I suppose to use it?

**Comment by maleadt** [comment]
What is the intended use? I've restructured the API to be consistend with the Random stdlib, and I find no `cached_state` there.

**Comment by robocop** [comment]
Hello. I have got somehow the same question.
Do you have a minimal implementation of a Monte-Carlo method on GPU?
I don't really know where I should ask the question (GPUArrays, CuArrays or CUDAnative?).

I would like to write a kernel that generates uniform random numbers (on the device) and compute for instance its empirical mean. 

I don't want to generate vectors of random numbers (with curand() for instance) because I don't need to store all the values. 

Thanks for any help.

**Comment by maleadt** [comment]
@robocop Sorry, didn't see your question. Please open a thread on Discourse if you still have this issue.
