### ISSUE TITLE
Base.copyto! override from CuArrays not currently in CUDA.jl

### ISSUE THREAD

**Issue by jakebolewski** [JuliaGPU/GPUArrays.jl#294]
When converting ClimateMachine.jl to use new CUDA package, the project was relying on these specializations defined in CuArrays:

https://github.com/JuliaGPU/GPUArrays.jl/blob/2e77a014c9c6453cded4b93b43ce35cf0a97b72a/src/host/abstractarray.jl#L78-L107

https://github.com/JuliaGPU/GPUArrays.jl/blob/2e77a014c9c6453cded4b93b43ce35cf0a97b72a/src/host/abstractarray.jl#L119

which do not seem to be in the new CUDA package (specifically `copyto!(::CuArray, ::Base.ReshapedArray`).   Is this an omission or should we move forward to doing something differently (an explicit copy to an `Array`)?

**Comment by maleadt** [comment]
Yes, in https://github.com/JuliaGPU/GPUArrays.jl/commit/c2dae91952901a7c00823d244611106e6400862e#diff-787e3d4983fad347c95f26af20b9c8fb I restricted `copyto!` interactions between CPU and GPU arrays to the `Array` type because using `AbstractArray` introduced a whole slew of ambiguities (since the other end, a GPU array, is also an `AbstractArray`).

I guess we could extend the set of allowed CPU sources/destinations to e.g. `Union{Array, ReshapedArray{<:Array}}` though, if you care about this.

**Comment by jakebolewski** [comment]
Thanks @maleadt that makes sense.  It seems like it would be be preferable to do the conversion to `Array` on the application side.  I think only `{<: AbstractArray}` would catch the called method in the application:

```
copyto!(::CUDA.CuArray{Float64,3,Nothing}, ::Base.ReshapedArray{Float64,3,SubArray{Float64,2,Array{Float64,3},Tuple{Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}})
```

**Comment by maleadt** [comment]
Yeah, it wouldn't cover that one. I think it only makes sense to accept CPU arrays on which we can call `pointer` for direct interfacing with CUDA libraries, but that's not very easy to dispatch on. Better to it in the application, but I'm happy to consider other options if you have any suggestions.
