### ISSUE TITLE
CuRAND.jl wrapper

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/GPUArrays.jl#32]
It would be nice to be able to have fast GPU generation of random numbers. Those algorithms are super good, so wrapping https://github.com/JuliaGPU/CURAND.jl would be very useful. Some way to use that to generate GPUArrays would be very helpful.

**Comment by SimonDanisch** [comment]
oh yeah, that'd be great!
 I think @vchuravy also has some methods to call those methods directly on the gpu in a kernel.
That'd be even nicer. Would be nice to figure out similar functionality for opencl!

**Comment by SimonDanisch** [comment]
I looked at RandomNumbers.jl and some of the methods in there should actually compile quite nicely for the GPU already.

**Comment by vchuravy** [comment]
Doing it directly from a kernel requires Cxx.jl so the dependency situation is messy.

**Comment by dfdx** [comment]
Note that CURAND.jl wraps cuRAND's **host API** while there's also **device API** that may be more useful in context of GPUArrays. If I understand correctly, wrapping device API would require writing a set of CUDAnative kernels the same way they do in C in their [examples](http://docs.nvidia.com/cuda/curand/device-api-overview.html#device-api-example). However, I can't find any example of calling CUDA functions from within a Julia/CUDAnative kernel. Is it possible at all?

**Comment by jekbradbury** [comment]
That's what https://github.com/JuliaGPU/CUDAnativelib.jl is for :D

**Comment by dfdx** [comment]
> That's what https://github.com/JuliaGPU/CUDAnativelib.jl is for :D

Which requires Cxx.jl... Now I see the point of @vchuravy's comment :)

**Comment by dfdx** [comment]
An organizational question. CURAND depends on CUDArt which has been marked as being phased out now. Luckily enough, it turned to be trivial to switch to CUDAdrv. Now, since package interface has been changed, I wonder what is the right thing to do with the updated version:

1. Bump package version, possibly breaking existing code.
2. Create an alternative package, say, CURAND2. 
3. Integrate new version directly into GPUArrays, leave the old CURAND code as is. 

The first option, though allowed by semantic versioning, maybe painful for existing users. The second one would result in a weird package name. The last option solves both issues, but does it fit into GPUArrays' vision?

**Comment by MikeInnes** [comment]
Just bump the version of curand. There's not much point in keeping the old, unmaintained api around.

**Comment by MikeInnes** [comment]
Closing in favour of https://github.com/JuliaGPU/CuArrays.jl/issues/9; this should just go in CuArrays.

**Comment by SimonDanisch** [comment]
GPUArrays also has a simple fallback that works for generating random numbers on the GPU! Should probably be documented better
