### ISSUE TITLE
Macro for loops

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/GPUArrays.jl#33]
Brought up here: https://discourse.julialang.org/t/list-of-most-desired-features-for-julia-v1-x/4481/80?u=chrisrackauckas

The idea is to transform the loops to broadcast:

```julia
@gpu for i in 2:length(A)-1
  A[i] = 2A[i] - A[i-1] - A[i+1]
end
```

That would be a really nice usability feature for writing stencils. Broadcast + views can be the implementation, right?

**Comment by SimonDanisch** [comment]
I've been thinking about this and concluded that there isn't a big
advantage over a closure + map like approach. one of the problems is, that
you can't just easily capture the used variables in a closure, since they
need to be uploaded in a special manner. Also, you need to figure out what
context to use. so you would end up with specifying the gpuarrays in the
macro header, at which point a mapidx like approach seems more natural.
Otherwise the macro needs to syntactically figure out what variables will
get captured and which of them are gpuarrays, which can be done, but I'm
not convinced that it's worth the effort.
So I'm all for something along the lines of:

```Julia
mapidx(1:x, A) do i, A
    ...
end
```
which seems equally usable and is easy to implement!

Am 28.06.2017 2:01 nachm. schrieb "Christopher Rackauckas" <
notifications@github.com>:

**Comment by gpu** [comment]
<sub>Off-topic: The good thing about a generic username is that, once in a while, you're notified about potentially interesting approaches and developments in projects that involve "something with GPUs". In this case, I already heard about the approaches of Julia targeting the GPU, during the parallelcon 2017, but this issue was at least a small "heads up" in this regard :-) </sub>

**Comment by SimonDanisch** [comment]
Ha that's fun :)
Btw, I think it'll be worth to make closures work and it should not be too difficult! 
We should be able to just do automatic converts, much like we do for the arguments to `gpu_call`.
The biggest difficulty will likely be, that how and what variables are caught isn't very transparent to me. @jeffbezanson, how much can we rely on the fact that this works:
```Julia
julia> function test()
       x = rand(10)
       ()-> x[1] + 2.0
       end
test (generic function with 1 method)
julia> y = test()
(::#3) (generic function with 1 method)
julia> y.x
10-element Array{Float64,1}:
```
Doing the same in global scope changes behaviour already, since it becomes a global ref.
Are there stable rules we could start relying on?

**Comment by maleadt** [comment]
This kind of interface now exists with GPUifyLoops.
