### ISSUE TITLE
rewrite `map` and `map!`?

### ISSUE THREAD

**Issue by MilkshakeForReal** [JuliaGPU/GPUArrays.jl#421]
I have a custom type that behaves like a `GPUArray`. I want to overload `map`, `mapreduce` and `map!`. It turns out overloading `mapreduce` is easy compared to the other two, since I can simply call `GPUArrays._mapreduce`, which does not limit the input types. So is reasonable to expect the same thing for `map` and `map!`?

**Comment by maleadt** [comment]
> overloading `mapreduce` is easy compared to the other two, since I can simply call `GPUArrays._mapreduce`

I'm not sure I'm following. Why do you need to call `_mapreduce` if you're implementing a Type that's `<:AbstractGPUArray`?

**Comment by MilkshakeForReal** [comment]
It's not a subtype of that. But when all its fields are, the custom type should behave like a GPUArray as well.

**Comment by maleadt** [comment]
> But when all its fields are, the custom type should behave like a GPUArray as well.

Why? If your type isn't a `<:AbstractGPUArray`, it shouldn't behave like one.

So IIUC you want to reuse the GPUArrays functionality without having an `<:AbstractGPUArray` type, which happens to work for mapreduce because we have an internal, untyped method `_mapreduce`. For one, you shouldn't use that function, it's an internal function without any stability guarantees. But more fundamentally, that's just not how things works. You can't expect us to split every method definition into that definition (typed for the sake of dispatch) + an untyped private method with the actual implementation. Or am I misunderstanding what you're asking? If so, please provide an actual example.

**Comment by MilkshakeForReal** [comment]
There's already an example in https://cuda.juliagpu.org/dev/tutorials/custom_structs/.  

I consider it quite natural to have `itp .* 0 ` not throwing me an error, i.e. behave like a GPUArray.

I did use `_mapreduce` and did get things to work, so I would leave it that if there's no better way.

**Comment by maleadt** [comment]
> There's already an example in https://cuda.juliagpu.org/dev/tutorials/custom_structs/.

Ah right, that's an interesting example. We're making use of the GPU-style broadcast there because of the CuArray argument `pts`, and not because of the `Interpolate{CuArray}` `itp`. So the point holds, `Interpolate` does not behave like a CuArray, and no other array operation will dispatch to a CUDA/GPUArray implementation, because it's not a subtype of AbstractGPUArray. It only happens with broadcast because the first argument passed is a CuArray.

**Comment by maleadt** [comment]
> I consider it quite natural to have `itp .* 0 ` not throwing me an error, i.e. behave like a GPUArray.

Except that doesn't work:

```
julia> itp .* 0
ERROR: MethodError: no method matching length(::Interpolate{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}})
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/Julia/depot/juliaup/julia-1.8.0-rc3+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:172
  length(::CUDA.CUSPARSE.CuSparseMatrix) at ~/Julia/pkg/CUDA/lib/cusparse/array.jl:223
  ...
Stacktrace:
 [1] _similar_shape(itr::Interpolate{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}, #unused#::Base.HasLength)
   @ Base ./array.jl:663
 [2] _collect(cont::UnitRange{Int64}, itr::Interpolate{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}, #unused#::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:718
 [3] collect(itr::Interpolate{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}})
   @ Base ./array.jl:712
 [4] broadcastable(x::Interpolate{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}})
   @ Base.Broadcast ./broadcast.jl:704
 [5] broadcasted(::Function, ::Interpolate{CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}, ::Int64)
   @ Base.Broadcast ./broadcast.jl:1301
 [6] top-level scope
   @ REPL[19]:1
 [7] top-level scope
   @ ~/Julia/pkg/CUDA/src/initialization.jl:52
```

**Comment by MilkshakeForReal** [comment]
Strange I didn't get notifications. I had got everything worked out pretty nicely. What I needed was `Interpolate<:AbstractArray`  (not `Interpolate<:AbstractGPUArray`).  It is not a subtype of  `CuArray`, but behaves like one when all its arguments are.
