### ISSUE TITLE
ArrayFire backend support

### ISSUE THREAD

**Issue by gaika** [JuliaGPU/GPUArrays.jl#60]
Do you think it would be worthwhile to add `ArrayFire.jl` as a  backend? How much work could it be? Would it be possible to interop with Arrays from different backends but backed by the same device?

**Comment by SimonDanisch** [comment]
You ask this at the right moment! We just decided to refactor GPUArrays to only contain generic, backendend independent julia code, and move the device specific code to [CuArrays](https://github.com/FluxML/CuArrays.jl) and [CLArrays](https://github.com/JuliaGPU/CLArrays.jl).
So it will becomes much easier for you to inherit from the GPUArray type and just be another backend! Not sure how much code we'll be able to share, though... 

Interop is possible and I made a [prototype](https://github.com/JuliaGPU/GPUArrays.jl/blob/master/src/backends/interop/af_cu.jl) at some point. 

We want to create a package like AcceleratedArrays at some point, which knows of all device specific backends and could host some glue code.

Btw, would you be interested to help with getting more algorithms in https://github.com/JuliaGPU/GPUBenchmarks.jl to work with ArrayFire?

**Comment by maleadt** [comment]
Going to close this, it would be nice to have this back-end but that's up to whoever wants to implement it :-)

**Comment by maartenvd** [comment]
one problem I see is that arrayfire also supports sparse matrices, and there is no fundamentally different type to distinguish between sparse and dense. Gpuarrays on the other hand defines abstractgpuarray to subtype densearray. Either you lie in arrayfire.jl, or the type definition in gpuarrays should be relaxed.

**Comment by maleadt** [comment]
For Sparse arrays, you probably want to be `<:AbstractSparseArray`, so lacking multiple inheritance you need a new type anyway. Or at least that's what CUDA.jl does.

**Comment by maartenvd** [comment]
I guess more to the point is that there's no real way yet to implement some kind of gpu_call for arrayfire?

**Comment by maleadt** [comment]
Yeah there's much more fundamental issues with supporting ArrayFire :-) IIRC they do have some kind of JIT, but I don't think that's exposed. Definitely not generic enough to implement `gpu_call`.

Out of curiosity, why are you looking into this? If you want to target an OpenCL platform, it would be better to revive OpenCL.jl and add a native back-end based on the SPIR-V compiler from oneAPI.jl.

**Comment by maleadt** [comment]
The kind of operations that work with ArrayFire arrays will also work on ROCArray/CuArray, so you can already write portable code. GPUArrays is an internal package to write portable code to implement such methods; as a user you don't really use GPUArrays. Unless you want to write portable kernel code, but nowadays KernelAbsctractions.jl is a better fit for that. Or, even simpler, using broadcast expressions. But these both aren't supported by ArrayFire because it doesn't have a compiler.

**Comment by maartenvd** [comment]
ok thanks! It sounds like I should try to get the hang of kernelabstractions

**Comment by ToucheSir** [comment]
> but it appears that opencl - the free open standard - is a bit abbandoned in julia

If we want to talk causality, OpenCL.jl is likely not actively developed because OpenCL itself has been abandoned. As long as the two biggest GPU vendors refuse to support ingesting SPIR-V IL in their implementations (case in point, NVIDIA recently released OpenCL 3.0 and explicitly said they wouldn't support SPIR-V), I don't see it ever being viable as a first-class backend for GPUCompiler and thus GPUArrays. So your confusion about the GPU stack is warranted, but unfortunately the root of that confusion stems from much further upstream than Julia.
